### ISSUE TITLE
ERROR:root:Uncaught exception running rule log_error: tuple index out of range

### ISSUE THREAD

**Issue by weihc02** [Hello-Linux/elastalert_wechat_plugin#5]
ERROR:root:Traceback (most recent call last):
  File "/opt/elastalert/elastalert/elastalert.py", line 1335, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/opt/elastalert/elastalert/elastalert.py", line 1424, in send_alert
    alert.alert(matches)
  File "elastalert_modules/wechat_qiye_alert.py", line 39, in alert
    body = self.create_alert_body(matches)
  File "elastalert/alerts.py", line 253, in create_alert_body
    body += unicode(BasicMatchString(self.rule, match))
  File "elastalert/alerts.py", line 144, in __str__
    self._add_custom_alert_text()
  File "elastalert/alerts.py", line 81, in _add_custom_alert_text
    alert_text = alert_text.format(*alert_text_values)
IndexError: tuple index out of range

ERROR:root:Uncaught exception running rule log_error: tuple index out of range

**Comment by Hello-Linux** [comment]
这个问题已经修复了

**Comment by cichuliubai** [comment]
我也碰到这个报错，修复是怎么修复的？
